### ISSUE TITLE
Can opticks be used to simulate high-energy photons?

### ISSUE THREAD

**Issue by AxEquals-b** [simoncblyth/opticks#2]
I have reviewed the Geant4 example CaTS and the papers related to JUNO simulations. It seems that they simulate optical photons at relatively low energy levels. Can Opticks be used to simulate photons at the GeV level?

**Comment by Sillyringo** [comment]
It seems that opticks is designed to simulate photons at several eV.

**Comment by simoncblyth** [comment]
Opticks is entirely focused on the simulation of optical photons, which are indeed in the few eV
energy range. Geant4 distinguishes low energy G4OpticalPhotons from high energy G4Gamma.
Opticks aims to replace Geant4 optical photons with an equivalent GPU implementation that is mainly of 
interest for the simulation of experiments that are limited by the high memory and time expense of dealing with large 
numbers of optical photons.
