### ISSUE TITLE
Build fails due to source files removed in sysrap (release v0.2.2)

### ISSUE THREAD

**Issue by plexoos** [simoncblyth/opticks#4]
In ca765a9ef2 SProc.hh was removed from the installed headers in `sysrap/CMakeLists.txt` but `boostrap/BOpticksResource.cc` still depends on it

**Comment by plexoos** [comment]
By reverting this change in `sysrap/CMakeLists.txt` the build of `boostrap` succeeds for me

**Comment by simoncblyth** [comment]
boostrap is a removed package that is has not been part of the standard build for several years
